name: Trigger auto deployment for container-app-4cdypfmbqnebu

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-4cdypfmbqnebu-AutoDeployTrigger-43774190-3887-4087-a2a3-8c2cbe3b1d31.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP4CDYPFMBQNEBU_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP4CDYPFMBQNEBU_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP4CDYPFMBQNEBU_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: defaultacrcontainerregistry99c9.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPP4CDYPFMBQNEBU_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP4CDYPFMBQNEBU_REGISTRY_PASSWORD }}
          containerAppName: container-app-4cdypfmbqnebu
          resourceGroup: expresssamplebc589e88
          imageToBuild: defaultacrcontainerregistry99c9.azurecr.io/container-app-4cdypfmbqnebu:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


